{% set name = "category_encoders" %}
{% set version = "2.5.0" %}
{% set sha256 = "ff72d21ddf62d829f43375c67ea4934c82947f9a0c5cbf9114838624db941420" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/scikit-learn-contrib/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  # noarch: python
  number: 0
  skip: true  # [py<37 or py>310]
  script:
    - {{ PYTHON }} -m pip install --no-deps -vvv .

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    # See our custom cbc.yaml for modified pinnnigs
    - numpy
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0
    - pandas >=1.0.5
    - patsy >=0.5.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0
    - pandas >=1.0.5
    - patsy >=0.5.1

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - category_encoders
  commands:
    - python -m pip check
    - pytest -vv -k "not (pandas_index or truncated_index)"

about:
  home: https://github.com/scikit-learn-contrib/categorical_encoding
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A collection sklearn transformers to encode categorical variables as numeric
  doc_url: https://contrib.scikit-learn.org/categorical-encoding
  description: |-
    A set of scikit-learn-style transformers for encoding categorical variables
    into numeric with different techniques. While ordinal, one-hot, and hashing
    encoders have similar equivalents in the existing scikit-learn version, the
    transformers in this library all share a few useful properties:
    - First-class support for pandas dataframes as an input (and optionally as
      output)
    - Can explicitly configure which columns in the data are encoded by name or
      index, or infer non-numeric columns regardless of input type
    - Can drop any columns with very low variance based on training set
      optionally
    - Portability: train a transformer on data, pickle it, reuse it later and
      get the same thing out.
    - Full compatibility with sklearn pipelines, input an array-like dataset
      like any other transformer

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
