{% set name = "category_encoders" %}
{% set version = "2.0.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc2fe178fe6b4dc6fbf4de6b9070151889255f6d1306ffc22e8de79e20c0c047

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir ."


requirements:
  host:
    - python
    - pip
  run:
    - numpy >=1.11.1
    - pandas >=0.20.1
    - patsy >=0.4.1
    - python
    - scikit-learn >=0.17.1
    - scipy >=0.17.0
    - statsmodels >=0.6.1

test:
  requires:
    - nose
    - python
    - unittest2
    - cython
  imports:
    - category_encoders
  commands:
    - nosetests category_encoders.tests

about:
  home: https://github.com/scikit-learn-contrib/categorical_encoding
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A set of scikit-learn-style transformers for encoding categorical variables into numeric by means of different techniques.
  doc_url: http://contrib.scikit-learn.org/categorical-encoding/

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
