{% set name = "category_encoders" %}
{% set version = "2.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scikit-learn-contrib/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 51d4c594cd102a3d30a4a00f3ffa62f73b3d2f4298e7a57df8a8046a8d7881f5
  patches:
    - patches/replace_pkg_resources_with_importlib.patch

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - scikit-learn >=0.20.0
    - scipy >=1.0.0
    - pandas >=1.5.3
    - patsy >=0.5.1
    - statsmodels >=0.9.0
    - numpy >=1.20.0
    - importlib-resources   # [py<39]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - category_encoders
  commands:
    - pip check
    - pytest -vv -k "not (pandas_index or truncated_index or test_extraValue)"

about:
  home: https://github.com/scikit-learn-contrib/category_encoders
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A collection sklearn transformers to encode categorical variables as numeric
  doc_url: https://contrib.scikit-learn.org/category_encoders
  dev_url: https://github.com/scikit-learn-contrib/category_encoders
  description: |-
    A set of scikit-learn-style transformers for encoding categorical variables
    into numeric with different techniques. While ordinal, one-hot, and hashing
    encoders have similar equivalents in the existing scikit-learn version, the
    transformers in this library all share a few useful properties:
    - First-class support for pandas dataframes as an input (and optionally as
      output)
    - Can explicitly configure which columns in the data are encoded by name or
      index, or infer non-numeric columns regardless of input type
    - Can drop any columns with very low variance based on training set
      optionally
    - Portability: train a transformer on data, pickle it, reuse it later and
      get the same thing out.
    - Full compatibility with sklearn pipelines, input an array-like dataset
      like any other transformer

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
