{% set name = "category_encoders" %}
{% set version = "1.2.6" %}
{% set sha256 = "99ccf0e451035d26dcfe9b21bea6835307b1ec090c289c5462001d3ad15f5bd0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy >=1.8.0
    - pandas >=0.16.0
    - patsy >=0.4.0
    - python
    - scikit-learn >=0.15.0
    - scipy >=0.9
    - statsmodels >=0.6.0

test:
  requires:
    - nose
    - python
  imports:
    - category_encoders
  commands:
    - nosetests category_encoders.tests

about:
  home: https://github.com/scikit-learn-contrib/categorical_encoding
  license: BSD-3-Clause
  license_family: BSD
  summary: A collection of sklearn transformers to encode categorical variables as numeric
  doc_url: http://contrib.scikit-learn.org/categorical-encoding/

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
