travis:
  secure:
    BINSTAR_TOKEN: LVbjYQTLH310FIgmZ5OE4XEiskJA8z0rWtRH/j7ADU8q+HPaRTpoXrq+C+H+Dq91u8LFDXWOU6w3O9Y+1GSm0bmPUOIOB/s940+fVs0FkRpjGqN2Pyu8yG2e/+c6+QqS3jYj1xTfTsdP2ZvLvVy9ufD3wRL7ZQJtky95hwNIIPwMxUJwCGANa9fX+ck7ZPIonZmgloBOC8H+GF5tT8XUGkcLD9CuHpOSut2EQnn73JrbG6jrAujCQYwFDIQJXuotMVfMgTqpsKOMdLvPS3sbruYtQwVaLtBpyBo7YhAAuAZjcJmFq1BdNmrirv75UIHZ+TglOEeEZl1N2EsKZVNPoNon9SmfBuv3yIWvLubGBAEyFeNP93quBliwkubGO0fXI0iCH0y0CUF6/nkGO9VKr89FXE7+X/Dt7ehAoBXZKl+N13geiBgFx387QaCDMN4KlprniW3sKr1+KZU7dpe5o//tP7xn54YDBah5i789yTdQ4kc79tdjzalFft8K1NDlBishZK/YsPVEnVkAeEnOdZj4A7cU3dhIYIgLmdGpMM/Ci8ouIkAWqhxNyBSkpIfi5sO2ez+35R/rCcaKYENEpPrUDSDDWiWKvFlOLgquq+fHxKTd4O7F1zrg2vKIptcFbqX0evgB97mwdIC+xAnh7V80ADCIAA266lbRkuQbrxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
