travis:
  secure:
    BINSTAR_TOKEN: OyOJ0k5b2M0OCNfzPqjnbecfFBYJvKdLKUzKgNR8w/j2sR8wzzPTBN0TrxAOsoHn+IevQRHIClCn7KdYs/+TeHhJ/w//0rSjXLV4JjQucZpKh8BgzxWMJg0sSIyF1vTQ3AIeBqf6rVwMjnAMBQWiUJfYucS6n9hyHFXipYybEfSQ8m3MCfJ26JEerGRoijssHkX7LqkY9KAg6gYQ63SUuJPDYh/eBd2HjS69/cwx6nPVYgisruQ5dQUKWR1TCs8pEAMVnyLKpSD6yDJxZwZKVTsbcuOX59/P2GYc/FVQxFNV9Dc1/UBLDQiQEg4i5LGK41g5lUu7Uvh1RdDjaDyPNr7h5PvR8r21moSIIATvcIa+0VWN1WRVBbYnTPq1xaeuBXfiNxSs03xuzKoUhCnGjskdDumnWnsSekjiNSTijCj2xfU7ABdteveq8mMKdns5ow/isA/ECXNY2q/5VLZszIG3M8IRFzjo0InV09dvZ1B7ZxBxKZ08UGMFc1DXwKnZozW+3gPYY1cgfveWW2EyEw0TGrrIcwmv/z1cFz+bGrdzbTOybujUX9eP8MAi/Fj6k9DSEFmcWAgV4SFSQ5OxpmPVH4ZGD3QEfJU4s8kR7gXsHErMHR/Z7x8wQeHTnDTEhvV5WacS+W7XCgDNRRFUH1s1HoKzY19VFMTwdvQ1cpA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
